[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "app-mfd"
version = "0.1.0"
description = "MFDApps Portal and API Gateway"
requires-python = ">=3.11"
